### ISSUE TITLE
Weekend activity

### ISSUE THREAD

**Issue by phenybutum** [phenybutum/newpract#1]
We need to decide what we going to do this weekend. We need to study, because exams are coming. But I want to go for a walk. So, what to do?

**Comment by vpaniush** [comment]
Well, i think that we should have a rest, because our brains are too tired :(

**Comment by phenybutum** [comment]
So, we need to decide where we want to go. It is nice that we decided to go somewhere.

**Comment by vpaniush** [comment]
So, let's go to Striyskiy park.

**Comment by phenybutum** [comment]
Fine.
